name: "Build Ren'Py Project using renConstruct"
author: 'kobaltcore'
description: "Utilize renConstruct to build distributions for Windows, Linux, macOS and Android"
inputs:
  project-dir:
    description: "The path to the directory where the project exists"
    required: true
    default: '.'
  config-file:
    description: "The path to the renConstruct config file relative to the root of the project"
    required: true
    default: 'config.yml'
  android-config-file:
    description: "The path to the android config json file relative to the root of the project"
    required: false
    default: '.android.json'

outputs:
  dir:
    description: "The directory where the distributed files exist"
  version:
    description: "The built version of the desktop project"
  android-numeric-game-version:
    description: "The numeric android version of the built version"
  sdk-version:
    description: "The SDK version used"
  android-package:
    description: "The package name inside the configured .android.json file"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.project-dir }}
    - ${{ inputs.config-file }}
    - ${{ inputs.android-config-file }}
branding:
  color: 'gray-dark'
  icon: 'archive'
