name: "Build Ren'Py (renpy) Project using renConstruct"
author: 'devorbitus'
description: "Utilize renConstruct to build distributions for Windows, Linux, macOS and Android"
inputs:
  config-file:
    description: "The path to the renConstruct config file relative to the root of the project"
    required: true
    default: 'config.yml'
  android-config-file:
    description: "The path to the android config JSON file relative to the root of the project"
    required: false
    default: '.android.json'
  shared-mount-path:
    description: "This path is kind of undocumented so placing it here in case it needs to be changed in the future without a code change to the action"
    required: false
    default: '/home/runner/work/_temp/_github_workflow'
  action-shared-mount-path:
    description: "This path is kind of undocumented so placing it here in case it needs to be changed in the future without a code change to the action. This is the path that container based actions will have access to as actions mounts the host directory into the container."
    required: false
    default: '/github/workflow'
  android-auto-upgrade-version:
    description: "Change this default to anything other than 'true' and it won't auto increment the version within the android config json file"
    required: false
    default: 'true'
outputs:
  local-dir:
    description: "The directory where the distributed files exist"
    value: ${{ steps.rba.outputs.local-dir }}
  action-dir:
    description: "The directory where the distributed files exist that another GitHub action can access"
    value: ${{ steps.rba.outputs.action-dir }}
  version:
    description: "The built version of the desktop project (config.version)"
    value: ${{ steps.rba.outputs.version }}
  android-numeric-game-version:
    description: "The numeric android version of the built version"
    value: ${{ steps.rba.outputs.android-numeric-game-version }}
  sdk-version:
    description: "The SDK version used"
    value: ${{ steps.rba.outputs.sdk-version }}
  android-package:
    description: "The package name inside the configured .android.json file"
    value: ${{ steps.rba.outputs.android-package }}
  build-name:
    description: "The official build name from the desktop project (build.name)"
    value: ${{ steps.rba.outputs.build-name }}
runs:
  using: 'composite'
  steps:
    - run: brew install coreutils
      shell: 'bash'
    - run: ${{ github.action_path }}/build.sh "${{ inputs.config-file }}" "${{ inputs.android-config-file }}" "${{ inputs.shared-mount-path }}" "${{ inputs.action-shared-mount-path }}" "${{ inputs.android-auto-upgrade-version }}" "${{ runner.os }}"
      id: rba
      shell: 'bash'
branding:
  color: 'blue'
  icon: 'package'
